### ISSUE TITLE
Static attributes from service not applied if device has static attributes

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/iotagent-node-lib#757] opened 2019-02-07 10:50 UTC
If a Service (device group) is provisioned with static_attributes and then a device is provisioned also with static_attributes (different attributes), when a measure is sent to the apikey-device_id, only static_attributes from device are applied.

If device is provisioned without static_attibutes, static_attributes from service are applied.

**Comment by fgalan** [comment] 2019-02-07 12:27
What should be expected behaviour? To provide the union set of both (config level and device level) static attributs (givin priority to the ones in device level if some attribute is in both sets)?

**Comment by manucarrace** [comment] 2019-02-23 09:48
Right. This is the expected behaviour

**Comment by fgalan** [comment] 2020-09-14 12:29
Fixed by PR https://github.com/telefonicaid/iotagent-node-lib/pull/908

**Comment by fgalan** [comment] 2020-09-14 12:30
Not sure if PR #908 fully solves this or is anything else pending... to be reviewed.

**Comment by Madhu-NEC** [comment] 2020-09-15 04:33
Hi @fgalan,

As per my understanding, PR #908 addresses this bug.
I request you to please let me know if anything is still pending?

Thanks!

**Comment by Madhu-NEC** [comment] 2020-09-25 09:37
Hi @fgalan ,

Is there any update on this issue?

Thanks!

**Comment by fgalan** [comment] 2020-09-30 15:49
Original issue says:

> If a Service (device group) is provisioned with static_attributes and then a device is provisioned also with static_attributes (different attributes), when a measure is sent to the apikey-device_id, only static_attributes from device are applied.
> 
> If device is provisioned without static_attibutes, static_attributes from service are applied.

Looking to the test added in #908 (just the descritpion, assuming the tests are correctly implemented) we have the following cases:

1. When a device provisioning request without static attributes arrives to the IoTA and static attribute is configured at group level
    * should store the device with static attributes provided in configuration
2. When a device provisioning request with static attributes arrives to the IoTA and static attribute is not configured at group level
    * should store the device with static attributes provided in device
3. When a device provisioning request with static attributes arrives to the IoTA and static attribute is also configured at group level
   * should store the device with static attributes provided in configuration as well as device
4. When a device provisioning request with static attributes arrives to the IoTA and same static attribute is also configured at group level
    * should store the device with static attributes provided in device

So, I understand they cover correctly the way of working so, after this analysis I think the issue is covered so I'll close it.

Of course, if somebody has a different opinion and think something is pending, tell so and I can re-open the issue.

**Closed by fgalan** 2020-09-30 15:49 UTC
Labels: bug
