### ISSUE TITLE
appendMode/IOTA_APPEND_MODE is not overwritten by autoprovision

### ISSUE THREAD

**Issue by djs0109** [telefonicaid/iotagent-node-lib#1301] opened 2022-11-22 08:00 UTC
from #1016

I found that the environment variable `appendMode/IOTA_APPEND_MODE` is not truly overwritten by `autoprovision` flag in group or device provision. However, it should be overwritten, as stated in [documentation](https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/installationguide.md).

What I try:
1. create a simple service group, while let the `appendMode/IOTA_APPEND_MODE=False` by default
POST /iot/services
```
{
 "services": [
   {
    "resource": "/iot/json",
    "apikey": "autoprovision",
    "expressionLanguage": "legacy",
    "explicitAttrs": false,
    "autoprovision": true
   }
 ]
}
```

2. I send an anonymous measurement. Then an entity is created **without any attributes**.
When I check the logs in Context Broker I found that the `actionType` is `update`
`INFO@2022-11-16T11:14:08.918Z  logTracing.cpp[148]: Request received: POST /v2/op/update, request payload (269 bytes): {"actionType":"update","entities":[{"humidity":{"type":"string","value":111, ... response code: 422`

3. I restart the IoTagent while setting the `IOTA_APPEND_MODE=true`.  I send the same measurement again. A new attribute is create d in the Context Broker. And I found that the `actionType` turn to `append` now
`INFO@2022-11-16T11:14:34.952Z  logTracing.cpp[148]: Request received: POST /v2/op/update, request payload (269 bytes): {"actionType":"append","entities":[{"humidity":{"type":"string","value":111, ... response code: 204`

**Comment by mapedraza** [comment] 2022-11-29 10:44
I just performed this test:

## Deployment

```yaml
  iot-agent:
    image: telefonicaiot/iotagent-json:latest
    hostname: iot-agent
    container_name: iot-agent
    depends_on:
      - mongo-db1
    expose:
      - "${IOTA_NORTH_PORT}"
      - "${IOTA_SOUTH_PORT}"
    ports:
      - "${IOTA_NORTH_PORT}:${IOTA_NORTH_PORT}" 
      - "${IOTA_SOUTH_PORT}:${IOTA_SOUTH_PORT}" 
    environment:
      - IOTA_LOG_LEVEL=DEBUG 
      - IOTA_MONGO_HOST=mongo-db1 
      - IOTA_MONGO_PORT=${MONGO_DB_PORT}
      - IOTA_MONGO_DB=iotagentjson 
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_CB_NGSI_VERSION=v2 
```

## Service creation

```json
curl -iX POST 'http://localhost:4041/iot/services' \
-H 'fiware-service: service' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
--data-raw '{
    "services": [
        {
            "apikey": "service1",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-1",
            "resource": "/iot/json",
            "explicitAttrs": false,
            "autoprovision": false,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        },
        {
            "apikey": "service2",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-2",
            "resource": "/iot/json",
            "explicitAttrs": false,
            "autoprovision": true,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        },
        {
            "apikey": "service3",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-3",
            "resource": "/iot/json",
            "explicitAttrs": true,
            "autoprovision": false,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        },
        {
            "apikey": "service4",
            "cbHost": "http://orion:1026",
            "entity_type": "Device-4",
            "resource": "/iot/json",
            "explicitAttrs": true,
            "autoprovision": true,
            "attributes": [
                {
                    "object_id": "s",
                    "name": "status",
                    "type": "Property"
                }
            ]
        }
    ]
}'
```

## Data sent

```bash
curl -L -X POST 'http://localhost:7896/iot/json?k=service1&i=dev1' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}' && \ 
curl -L -X POST 'http://localhost:7896/iot/json?k=service2&i=dev2' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}' && \ 
curl -L -X POST 'http://localhost:7896/iot/json?k=service3&i=dev3' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}' && \ 
curl -L -X POST 'http://localhost:7896/iot/json?k=service4&i=dev4' \
-H 'Content-Type: application/json' \
--data-raw '{ "t": 5}'
```

## Result

```json
curl -vX GET 'http://localhost:1026/v2/entities' \
-H 'fiware-service: service' \
-H 'fiware-servicepath: /' | python -mjson.tool


[
    {
        "TimeInstant": {
            "metadata": {},
            "type": "DateTime",
            "value": "2022-11-29T10:33:55.323Z"
        },
        "id": "Device-2:dev2",
        "status": {
            "metadata": {},
            "type": "Property",
            "value": null
        },
        "type": "Device-2"
    },
    {
        "TimeInstant": {
            "metadata": {},
            "type": "DateTime",
            "value": "2022-11-29T10:33:55.557Z"
        },
        "id": "Device-4:dev4",
        "status": {
            "metadata": {},
            "type": "Property",
            "value": null
        },
        "type": "Device-4"
    }
]
```

## Conclusions 

As we can see, all 2 measurements corresponding to the 2 groups that `autoprovision: true` were persisted. 
Thus, the flag seems working properly. 

Could you please reproduce the steps described here? Could you provide a similar report with curl requests and IoTA deployment / config?

**Comment by djs0109** [comment] 2022-12-01 09:39
Yes of course!

## Deployment

```yml
  iot-agent:
    image: telefonicaiot/iotagent-json:latest
    hostname: iot-agent
    container_name: "iot-agent"
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "4041:4041"
      - "7896:7896"
    networks:
      - fiware
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_HTTP_PORT=7896
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
      - IOTA_DEFAULT_TRANSPORT=MQTT
      - IOTA_MQTT_PROTOCOL=mqtt
      - IOTA_MQTT_KEEPALIVE=60
```

## Service Creation
same as above

## Data sent
The data is sent via MQTT
```
topic: /json/service1/dev1/attrs
payload: {"t":5}


topic: /json/service2/dev2/attrs
payload: {"t":5}


topic: /json/service3/dev3/attrs
payload: {"t":5}


topic: /json/service4/dev4/attrs
payload: {"t":5}
```

## Results
```yml
curl --location --request GET 'http://localhost:1026/v2/entities/' \
--header 'fiware-service: test' \
--header 'fiware-servicepath: /'

[
    {
        "id": "Device-2:dev2",
        "type": "Device-2",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:13:51.754Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        }
    },
    {
        "id": "Device-4:dev4",
        "type": "Device-4",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:14:01.982Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        }
    }
]
```

## Conclusions
We see that service 1, 3, 4 works as expected, but service 2 did not. In service 2, where `"explicitAttrs": false` and `"autoprovision": true`, the expected behavior is:
1. The entity should be created (✓)
2. The attribute "t" should also be created (x)

If we add `- IOTA_APPEND_MODE=true` to `env`, and then **only** send `dev2` data again, we can see that the attribute `t` is crceated. 

```yml
curl --location --request GET 'http://localhost:1026/v2/entities/' \
--header 'fiware-service: test' \
--header 'fiware-servicepath: /'

[
    {
        "id": "Device-2:dev2",
        "type": "Device-2",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:30:28.812Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        },
        "t": {
            "type": "string",
            "value": 5,
            "metadata": {
                "TimeInstant": {
                    "type": "DateTime",
                    "value": "2022-12-01T09:30:28.812Z"
                }
            }
        }
    },
    {
        "id": "Device-4:dev4",
        "type": "Device-4",
        "TimeInstant": {
            "type": "DateTime",
            "value": "2022-12-01T09:14:01.982Z",
            "metadata": {}
        },
        "status": {
            "type": "Property",
            "value": null,
            "metadata": {}
        }
    }
]
```

## Summary
`autoprovision` can not overwrite `appendMode/IOTA_APPEND_MODE`

**Comment by mapedraza** [comment] 2022-12-19 08:26
I think here there is a bit of confusion with some concepts, since there are multiples configurations that impacts on the IoT Agent and also on the Context Broker requests.

So if we analyse what happens when using the `appendMode=true`. 

The IoT agent perform 2 queries to the CB, as we can see in the following log:

``` 
fiware-iot-agent  | time=2022-12-15T11:12:08.823Z | lvl=DEBUG | corr=94b62258-a42b-4757-ae10-c7871149b794 | trans=94b62258-a42b-4757-ae10-c7871149b794 | op=IoTAgentNGSI.Request | from=n/a | srv=service | subsrv=/ | msg=Options: {
fiware-iot-agent  |     "url": "http://orion:1026/v2/entities?options=upsert",
fiware-iot-agent  |     "method": "POST",
fiware-iot-agent  |     "json": {
fiware-iot-agent  |         "id": "Device-2:dev2",
fiware-iot-agent  |         "type": "Device-2",
fiware-iot-agent  |         "status": {
fiware-iot-agent  |             "type": "Property",
fiware-iot-agent  |             "value": null
fiware-iot-agent  |         },
fiware-iot-agent  |         "TimeInstant": {
fiware-iot-agent  |             "type": "DateTime",
fiware-iot-agent  |             "value": "2022-12-15T11:12:08.818Z"
fiware-iot-agent  |         }
fiware-iot-agent  |     },
fiware-iot-agent  |     "headers": {
fiware-iot-agent  |         "fiware-service": "service",
fiware-iot-agent  |         "fiware-servicepath": "/",
fiware-iot-agent  |         "fiware-correlator": "94b62258-a42b-4757-ae10-c7871149b794"
fiware-iot-agent  |     }
fiware-iot-agent  | } | comp=IoTAgent




fiware-orion      | time=2022-12-15T11:12:08.886Z | lvl=INFO | corr=94b62258-a42b-4757-ae10-c7871149b794 | trans=1671102692-165-00000000008 | from=172.18.1.4 | srv=service | subsrv=/ | comp=Orion | op=logTracing.cpp[148]:logInfoRequestWithPayload | msg=Request received: POST /v2/entities?options=upsert, request payload (151 bytes): {"id":"Device-2:dev2","type":"Device-2","status":{"type":"Property","value":null},"TimeInstant":{"type":"DateTime","value":"2022-12-15T11:12:08.818Z"}}, response code: 204











fiware-iot-agent  |  | comp=IoTAgent
fiware-iot-agent  | time=2022-12-15T11:12:08.937Z | lvl=DEBUG | corr=94b62258-a42b-4757-ae10-c7871149b794 | trans=94b62258-a42b-4757-ae10-c7871149b794 | op=IoTAgentNGSI.Request | from=n/a | srv=service | subsrv=/ | msg=Options: {
fiware-iot-agent  |     "url": "http://orion:1026/v2/entities/Device-2:dev2/attrs?type=Device-2",
fiware-iot-agent  |     "method": "PATCH",
fiware-iot-agent  |     "headers": {
fiware-iot-agent  |         "fiware-service": "service",
fiware-iot-agent  |         "fiware-servicepath": "/"
fiware-iot-agent  |     },
fiware-iot-agent  |     "json": {
fiware-iot-agent  |         "t": {
fiware-iot-agent  |             "type": "string",
fiware-iot-agent  |             "value": 5,
fiware-iot-agent  |             "metadata": {
fiware-iot-agent  |                 "TimeInstant": {
fiware-iot-agent  |                     "type": "DateTime",
fiware-iot-agent  |                     "value": "2022-12-15T11:12:08.936Z"
fiware-iot-agent  |                 }
fiware-iot-agent  |             }
fiware-iot-agent  |         },
fiware-iot-agent  |         "TimeInstant": {
fiware-iot-agent  |             "type": "DateTime",
fiware-iot-agent  |             "value": "2022-12-15T11:12:08.936Z"
fiware-iot-agent  |         }
fiware-iot-agent  |     }
fiware-iot-agent  | } | comp=IoTAgent


fiware-orion      | time=2022-12-15T11:12:08.943Z | lvl=INFO | corr=50ebe5f4-7c69-11ed-aa1a-0242ac120103 | trans=1671102692-165-00000000009 | from=172.18.1.4 | srv=service | subsrv=/ | comp=Orion | op=logTracing.cpp[148]:logInfoRequestWithPayload | msg=Request received: PATCH /v2/entities/Device-2:dev2/attrs?type=Device-2, request payload (184 bytes): {"t":{"type":"string","value":5,"metadata":{"TimeInstant":{"type":"DateTime","value":"2022-12-15T11:12:08.936Z"}}},"TimeInstant":{"type":"DateTime","value":"2022-12-15T11:12:08.936Z"}}, response code: 422
fiware-iot-agent  | time=2022-12-15T11:12:08.945Z | lvl=DEBUG | corr=94b62258-a42b-4757-ae10-c7871149b794 | trans=94b62258-a42b-4757-ae10-c7871149b794 | op=IoTAgentNGSI.Request | from=n/a | srv=service | subsrv=/ | msg=Response {
fiware-iot-agent  |     "error": "Unprocessable",
fiware-iot-agent  |     "description": "one or more of the attributes in the request do not exist: [ t ]"
fiware-iot-agent  | } | comp=IoTAgent
```

The first request creates the device (this is effectively the autoprovision) according to the attributes included in the service or device definition. 

The second one, updates the data received in the south port. 

What explicitAttrs does is to pass to the CB update request only the attributes specified in the provision, and, in this case, it is passing the attributes not provided in the provision, so, it is working. The problem is that the data is not persisted, but it is jut because they are nor created into the Context Broker. 

For that purpose is used `appendMode=true`, in order to append the attribute even if it was not created.

So, as a summary:
- If `autoprovision=true`, the IoTA will do a initial request creating the entity into the context broker with the static and active attributes provisioned. This is something related with the southbound.
- If `explicitAttrs=true`, the IoTA will allow to pass to update requests only the attributes defined in the device or service provision. Otherwise, measures not defined in the service group or the device provision, will be passed to the CB with the same name of the parameter (I.E: `"t":5`). This is something related with the southbound.
- If `appendMode=true`, the IoTA will use and append request instead of the update, so, it will store the attributes even if they are not present int the entity. This can impact on "autoprovision" behaviour, but it is a "different" concept, since it is a config to setup how the IoT interacts with the context broker, this is something relate with the northbound.

**Comment by djs0109** [comment] 2022-12-22 08:25
Thank you for the explanation, that really makes sense 👍 During these tests, I would like to ask another tiny question: Why does IoTA always use `string` as data type, even if the actual value is a number?

**Comment by fgalan** [comment] 2023-01-10 12:02
Expand documentation in this section: https://github.com/telefonicaid/iotagent-node-lib/blob/master/doc/advanced-topics.md#autoprovision-configuration-autoprovision

**Comment by mapedraza** [comment] 2023-03-07 11:22
@djs0109 Please could you close this issue if it was solved? After clarifying how those parameters, and including them into the documentation (PR #1306), seems this issue is solved

**Closed** 2023-03-07 11:43 UTC
