### ISSUE TITLE
Automatic device provisioning by means of Configuration Group fails due to a bug in findConfigurationGroup function.

### ISSUE THREAD

**Issue by mgaggero** [telefonicaid/iotagent-node-lib#544] opened 2017-04-13 17:16 UTC
Using iotagent-json and Configuration Group, automatic device provisioning fails apparently because the Configuration Group  is not correctly retrieved.
In order to reproduce, using the last docker image of iotagent-json, the group definition is:

```
curl -X POST \
  http://localhost:4041/iot/services \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  -H 'fiware-service: meteo' \
  -H 'fiware-servicepath: /building1' \
  -d '{
  "services": [
    {
      "apikey": "AABBCCDD",
      "entity_type": "owls_station",
      "resource": "",
	  "attributes": [
                { "object_id":  "t", "name": "temperature", "type": "float" },
                { "object_id":  "h", "name": "humidity",    "type": "float" }
        ]
    }
  ]
}'
```

the data sent by the new device 'station1' using MQTT and non-default key 'AABBCCDD':

`mosquitto_pub -t "/AABBCCDD/station1/attrs" -m '{"h": 49.15, "t": 25.9}'`

The bug seems to be in file _lib/services/devices/deviceService.js_, function _findConfigurationGroup_:

```
        config.getGroupRegistry().findBy(['service', 'subservice', 'type'])(
            deviceObj.service,
            deviceObj.subservice,
            deviceObj.type,
            handlerGroupFind);
```

Using the following function instead, auto provisioning works fine:
```
        config.getGroupRegistry().findType(
            deviceObj.service,
            deviceObj.subservice,
            deviceObj.type,
            handlerGroupFind);
```

Has anyone else experienced the same problem?

**Comment by agaldemas** [comment] 2018-02-22 18:31
the problem is still there, I face the same issue, the code has not been changed
did you test on your own, the modification you propose ?

**Comment by fgalan** [comment] 2018-02-23 11:19
In addition to @agaldemas comment... it would be great to know if `grunt test` goes ok after the proposed modification.

**Comment by agaldemas** [comment] 2018-02-23 11:38
Hello, I've tested @fgalan modification by modifying directly the file in the docker container, (since I didn't managed to build an image with my forked repositories), but It works fine
should it be possible the modification to be integrated on this repository ?
Thanks in advance

**Comment by fgalan** [comment] 2018-02-23 12:40
@agaldemas did you run `grunt test` on the modified code? Could you post a comment with the output, pls?

**Comment by fgalan** [comment] 2018-02-23 13:13
If the `grunt test goes ok`, I'd suggest as next step you create a pull request with the proposed change. Eventually that PR will be reviewed and merged.

**Comment by agaldemas** [comment] 2018-02-23 13:45
find the results of grunt test attached (test-res.txt)
there's some failed, but due to my environment
[test-res.txt](https://github.com/telefonicaid/iotagent-node-lib/files/1751820/test-res.txt)

**Comment by agaldemas** [comment] 2018-02-23 13:53
I started my mongodb container and the test is OK
[test-res.txt](https://github.com/telefonicaid/iotagent-node-lib/files/1751858/test-res.txt)

**Comment by mgaggero** [comment] 2018-02-23 13:57
@agaldemas , actually we are running our servers with this modification. As you have already pointed out, if cannot build the docker image, it is enough to copy the files straight to the running container.
@fgalan I have already performed the Grunt test in the past and all went ok. But in this moment I cannot manage to reach the server. @agaldemas can you give a try in your container?

**Comment by mgaggero** [comment] 2018-02-23 13:59
@agaldemas apologize, I have just received your test result right now.

**Comment by agaldemas** [comment] 2018-02-23 14:20
Hi, as proposed by @fgalan, I've made a "pull-request" for merge #580

**Comment by agaldemas** [comment] 2018-02-23 14:20
thanks for your feedback

**Comment by fgalan** [comment] 2018-02-23 14:44
I see PR #580, but it is not correct (see comments in #580) itself.

**Comment by mgaggero** [comment] 2018-02-23 16:59
@fgalan in PR https://github.com/telefonicaid/iotagent-node-lib/pull/551 there is already a fix for #544 with a fix for #550. It is possible to review and merge PR #551 instead of create another PR just for #544?

**Comment by fgalan** [comment] 2018-02-23 17:44
> @fgalan in PR #551 there is already a fix for #544 with a fix for #550. It is possible to review and merge PR #551 instead of create another PR just for #544?

Makes sense

(I didn't realized about that PR... when a PR addresses and issue it is a good idea to include a "Fixes a #number_of_issue" in the PR body and a "Fixed by #number_of_pr" in a comment in the issue. That way all gets linked).

**Comment by agaldemas** [comment] 2018-02-23 18:06
Sorry I am not à github warrior in particular on pull request you can close
the PR if you want as soon as you fix the issue in the next release
Thanks

Le 23 févr. 2018 18:44, "Fermín Galán Márquez" <notifications@github.com> a
écrit :

**Comment by fgalan** [comment] 2018-02-23 18:20
> Sorry I am not à github warrior in particular on pull request you can close the PR if you want as soon as you fix the issue in the next release

Actually, after @mgaggero recent feedback, it seems there is already a PR on the table that fixes the issue. That PR is #551 

It would be great if you could have a look or event test with that branch in order to see if it solves the issue. In that case, please provide a "LGTM" comment (Looks Good To Me) on the PR. 

Thanks!

**Comment by agaldemas** [comment] 2018-02-24 15:42
Hello,
I confirm that @mgaggero proposed fix works OK, in my docker environnement, the behaviour is : 
At the first update through iotagent-ul
the service configuration is got from the MongoDB, no device is created, and the entity is created with the dynamic attributes, **but the static attributes defined at service level are not propagated in the entity**, 
subsequent update, on iotagent update the entity.

**Comment by fgalan** [comment] 2018-03-02 16:03
Once PR #551 has been merged, I undestand this issue can be closed, so I'm doing so. Please, tell me otherwise if I'm wrong @mgaggero @agaldemas

**Closed by fgalan** 2018-03-02 16:03 UTC

**Comment by agaldemas** [comment] 2018-03-05 14:48
OK for me !

*Alain Galdemas*

+33 (0) 608 640 961

2018-03-02 17:03 GMT+01:00 Fermín Galán Márquez <notifications@github.com>:
