### ISSUE TITLE
explicitAttrs: "true" is not true

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/iotagent-node-lib#1291] opened 2022-09-02 12:07 UTC
explicitAttrs: true
behaves as expected

but 

explicitAttrs:"true" or explicitAttrs:"m0==null?[]:true"
doesn't.

**Comment by MayankSingh-NEC** [comment] 2022-09-12 06:49
Hi @mrutid  and @fgalan  , could you please provide me the detailed description regarding the issue? also, could you attach the specific link or data to reproduce this issue. Thank you.

**Comment by mapedraza** [comment] 2022-09-13 09:24
Hi @MayankSingh-NEC, thanks for your willingness to contribute to the IoT Agent. Somehow this is a corner case, so this is nor urgent. It would be addressed later when refactoring the code related in the iotagent-node-lib.

**Comment by MayankSingh-NEC** [comment] 2022-11-15 06:24
Hi @mrutid  and @fgalan  , I'm not able to reproduce this issue. As, it is completely working fine in my system, using the default configs. PFA.

1. Group Provisioning

curl -iX POST \
  'http://localhost:4041/iot/services' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: myHome' \
  -H 'fiware-servicepath: /environment' \
  -d '{
 "services": [
   {
     "apikey":      "4jggokgpepnvsb2uv4s40d59ov",
     "cbHost":     "http://orion:1026",
     "entity_type": "Device",
     "resource":    "/iot/d",
	 "explicitAttrs": "m0==null?[]:true" or "true"
    }
 ]
}'

Note: Response can be seen in the iotagent-json logs. Attached in the file.
![1](https://user-images.githubusercontent.com/103482738/201842331-80df7deb-8a51-4603-9c95-3ab00f3f4ff4.PNG)
![2](https://user-images.githubusercontent.com/103482738/201842569-f5032e4e-cf5a-418f-b1e7-2bddd3f6061d.PNG)

**Comment by mapedraza** [comment] 2022-11-15 11:28
Thank @MayankSingh-NEC for testing the issue. You are just checking the group provision. This was working well. 

The problem behind this is how the agent is working when sending the measures. You should test If sending a measure m0, then the measures should not be propagated to the CB. Everything else should be persisted.

Having said that, this problem was already analysed and identified. The challenge here is the logic is distributed across the codebase, so it is not a simple fix. We are waiting until refactoring the code related with explicitAttrs, that would simplify the fix.

**Comment by AlvaroVega** [comment] 2023-03-27 07:25
This issue is fixed by https://github.com/telefonicaid/iotagent-node-lib/pull/1314

**Comment by fgalan** [comment] 2023-03-27 07:31
@MayankSingh-NEC could you check again (using master branch) and provide feedback, please? Thanks!

**Comment by MayankSingh-NEC** [comment] 2023-04-18 11:22
> @MayankSingh-NEC could you check again (using master branch) and provide feedback, please? Thanks!

Hi @fgalan , I've tested and verified that now, it's working fine. Thanks :))

**Closed** 2023-04-19 17:03 UTC
